---
name: Check if the workflow requires approval
on:
  workflow_call:
    outputs:
      is-require-approval:
        description: The CI image version for Linux build
        value: ${{ jobs.Require-Approval.outputs.output-is-require-approval }}

jobs:
  Require-Approval:
    runs-on: ubuntu-latest
    outputs:
      output-is-require-approval: ${{ steps.step-is-require-approval.outputs.is-require-approval }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Get CodeOwner List
        id: step-is-require-approval
        run: |
          github_event=${{ github.event_name }}
          author=${{ github.event.pull_request.user.login }}

          if [[ "$github_event" == "push" ]]; then
            echo "Push event does not need approval."
            echo "is-require-approval=ml-commons-cicd-env" >> $GITHUB_OUTPUT
          else
            # Handle Pull Request events

            # Check if the PR is triggered by opensearch-trigger-bot
            if [[ "$author" == "opensearch-trigger-bot[bot]" ]]; then
              echo "PR triggered by opensearch-trigger-bot. No approval needed."
              echo "is-require-approval=ml-commons-cicd-env" >> $GITHUB_OUTPUT
            else
              # Check if the author is in the approvers list
              approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')
              is_approved=false
              for approver in $approvers; do
                if [[ "$approver" == "$author" ]]; then
                  is_approved=true
                  break
                fi
              done
              if [[ "$is_approved" == "true" ]]; then
                echo "$author is in the approval list."
                echo "is-require-approval=ml-commons-cicd-env" >> $GITHUB_OUTPUT
              else
                echo "$author is not in the approval list."
                echo "is-require-approval=ml-commons-cicd-env-require-approval" >> $GITHUB_OUTPUT
              fi
            fi
          fi
